let data={subjects:['Mathematics','C++','DSA'],sessions:[],version:2},page='home',selectedSubject='',timerId=null,elapsed=0,timerStartedAt=0,timerBaseElapsed=0,viewDate=new Date(),statsYear=new Date().getFullYear();
// Timer is wall-clock based: the interval is only a display refresher. The elapsed value is always derived from the timestamps, so renderer throttling cannot make study time disappear.
let timerLastUiRefresh=0;

const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const key=d=>{let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const fmt=s=>{s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor(s%3600/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const hours=s=>(s/3600).toFixed(1);
const liveElapsed=()=>timerId&&timerStartedAt?timerBaseElapsed+Math.max(0,Math.floor((Date.now()-timerStartedAt)/1000)):elapsed;
const refreshTimerNow=()=>{ if(!timerId||!timerStartedAt)return; elapsed=liveElapsed(); timerLastUiRefresh=Date.now(); const c=$('#clock'); if(c)c.textContent=fmt(elapsed); const lv=$('#level'); if(lv)lv.textContent=level(); };

const total=()=>data.sessions.reduce((a,s)=>a+s.seconds,0)+liveElapsed();
const level=()=>Math.floor(total()/3600/10)+1;
const monthSessions=(y,m)=>data.sessions.filter(s=>{let d=new Date(s.started);return d.getFullYear()===y&&d.getMonth()===m});
const dayTotal=k=>data.sessions.filter(s=>key(s.started)===k).reduce((a,s)=>a+s.seconds,0);
const save=()=>window.studyAPI.save(data);
function render(){ if(timerId) elapsed=liveElapsed(); $('#level').textContent=level(); const titles={home:'Overview',timer:'Timer',calendar:'Calendar',analytics:'Statistics',consistency:'Consistency',history:'History',growth:'Growth'};$('#title').textContent=titles[page];({home, timer:timerPage, calendar:calendarPage, analytics:analyticsPage, consistency:consistencyPage, history:historyPage, growth:growthPage}[page])(); }
function home(){let now=new Date(),today=dayTotal(key(now)),week=data.sessions.filter(s=>{let d=new Date(s.started);return (now-d)/86400000<7}).reduce((a,s)=>a+s.seconds,0),active=new Set(data.sessions.map(s=>key(s.started))).size;
$('#content').innerHTML=`<div class="page"><div class="grid g4"><div class="card metric"><span class="eyebrow2">TODAY</span><strong>${fmt(today)}</strong><small>recorded study time</small></div><div class="card metric"><span class="eyebrow2">LAST 7 DAYS</span><strong>${fmt(week)}</strong><small>rolling week</small></div><div class="card metric"><span class="eyebrow2">ALL TIME</span><strong>${hours(total())}h</strong><small>${data.sessions.length} sessions</small></div><div class="card metric"><span class="eyebrow2">ACTIVE DAYS</span><strong>${active}</strong><small>days with recorded time</small></div></div>
<div class="grid g2 mt"><div class="card"><div class="cardhead"><h3>Last 14 days</h3><button class="linkbtn" id="goCal">Open calendar</button></div>${dailyBars(14)}</div><div class="card"><h3>Subject distribution</h3>${pie(subjectTotals())}</div></div>
<div class="grid g2 mt"><div class="card"><h3>Consistency heatmap</h3>${yearHeatmap(new Date().getFullYear(),false)}</div><div class="card"><h3>Study patterns</h3>${patternCards()}</div></div></div>`;$('#goCal').onclick=()=>{page='calendar';syncNav();render()};}
function patternCards(){let longest=Math.max(0,...data.sessions.map(s=>s.seconds)),a=Array(24).fill(0);data.sessions.forEach(s=>a[new Date(s.started).getHours()]+=s.seconds);let bh=a.indexOf(Math.max(...a));return `<div class="pattern-grid"><div><small>Longest session</small><b>${fmt(longest)}</b></div><div><small>Best hour</small><b>${String(bh).padStart(2,'0')}:00</b></div><div><small>Avg session</small><b>${data.sessions.length?fmt(total()/data.sessions.length):'00:00:00'}</b></div><div><small>Current streak</small><b>${streak()}d</b></div></div>`}
function timerPage(){if(!selectedSubject&&data.subjects.length)selectedSubject=data.subjects[0];if(timerId)elapsed=liveElapsed();$('#content').innerHTML=`<div class="page"><div class="grid g2"><div class="card timerbox"><span class="eyebrow2">LIVE STUDY TIMER</span><div class="clock" id="clock">${fmt(elapsed)}</div><div class="timer-sub">${selectedSubject?esc(selectedSubject):'No subject selected'}</div><div class="controls"><button class="primary" id="startBtn">${timerId?'Pause':'Start'}</button><button id="finishBtn">Finish session</button></div><div class="muted">Pause whenever you need. Only completed sessions are saved.</div></div><div class="card"><div class="cardhead"><h3>Subjects</h3><button class="primary small" id="addSubject">+ Add</button></div><div id="subjectsList" class="subjects-list">${subjectEditor()}</div></div></div><div class="card mt"><div class="cardhead"><h3>Recent sessions</h3><button class="linkbtn" id="historyBtn">Full history</button></div>${recentRows(8)}</div></div>`;bindTimer();}
function subjectEditor(){return data.subjects.length?data.subjects.map((s,i)=>`<div class="subject-item ${s===selectedSubject?'selected':''}"><button class="subject-main" data-select-index="${i}"><span class="dot d${i%6}"></span><span>${esc(s)}</span></button><div class="subject-actions"><button class="iconbtn" data-rename-index="${i}" title="Rename subject" aria-label="Rename ${esc(s)}">✎</button><button class="iconbtn danger" data-delete-index="${i}" title="Delete subject" aria-label="Delete ${esc(s)}">×</button></div></div>`).join(''):'<div class="empty">No subjects. Add one to begin.</div>'}
function subjectDialog(title, initial='', actionLabel='Save'){return new Promise(resolve=>{let old=document.getElementById('subjectModal');if(old)old.remove();const modal=document.createElement('div');modal.id='subjectModal';modal.className='modal-backdrop';modal.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="subjectModalTitle"><div class="modal-head"><h3 id="subjectModalTitle">${esc(title)}</h3><button class="modal-close" id="modalCancel" type="button">×</button></div><input id="subjectInput" class="modal-input" type="text" maxlength="80" autocomplete="off" spellcheck="false" value="${esc(initial)}" placeholder="e.g. Operating Systems"><div id="subjectError" class="modal-error"></div><div class="modal-actions"><button id="modalCancel2" type="button">Cancel</button><button id="modalSave" class="primary" type="button">${esc(actionLabel)}</button></div></div>`;document.body.appendChild(modal);const input=modal.querySelector('#subjectInput'),error=modal.querySelector('#subjectError');let done=false;const close=value=>{if(done)return;done=true;modal.remove();resolve(value)};const submit=()=>{const value=input.value.trim();if(!value){error.textContent='Enter a subject name.';input.focus();return}close(value)};modal.querySelector('#modalSave').onclick=submit;modal.querySelector('#modalCancel').onclick=()=>close(null);modal.querySelector('#modalCancel2').onclick=()=>close(null);modal.addEventListener('mousedown',e=>{if(e.target===modal)close(null)});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();submit()}else if(e.key==='Escape'){e.preventDefault();close(null)}});requestAnimationFrame(()=>{input.focus();input.select()});});}

async function confirmDialog(title,message,confirmLabel='Delete'){return new Promise(resolve=>{let old=document.getElementById('confirmModal');if(old)old.remove();const modal=document.createElement('div');modal.id='confirmModal';modal.className='modal-backdrop';modal.innerHTML=`<div class="modal-card" role="dialog" aria-modal="true"><div class="modal-head"><h3>${esc(title)}</h3><button class="modal-close" id="confirmX" type="button">×</button></div><div class="muted confirm-message">${esc(message)}</div><div class="modal-actions"><button id="confirmNo" type="button">Cancel</button><button id="confirmYes" class="primary danger-action" type="button">${esc(confirmLabel)}</button></div></div>`;document.body.appendChild(modal);let done=false;const close=value=>{if(done)return;done=true;modal.remove();resolve(value)};modal.querySelector('#confirmYes').onclick=()=>close(true);modal.querySelector('#confirmNo').onclick=()=>close(false);modal.querySelector('#confirmX').onclick=()=>close(false);modal.addEventListener('mousedown',e=>{if(e.target===modal)close(false)});document.addEventListener('keydown',function key(e){if(e.key==='Escape'){document.removeEventListener('keydown',key);close(false)}});requestAnimationFrame(()=>modal.querySelector('#confirmYes').focus())})}
function updateLiveClock(){refreshTimerNow();}
function startTimer(){if(timerId)return;timerBaseElapsed=elapsed;timerStartedAt=Date.now();timerId=setInterval(refreshTimerNow,250);refreshTimerNow();}
function pauseTimer(){if(!timerId)return;refreshTimerNow();clearInterval(timerId);timerId=null;timerStartedAt=0;timerBaseElapsed=elapsed;render();}

// Re-sync immediately whenever Electron/Windows resumes or the app becomes visible again.
window.addEventListener('focus',refreshTimerNow);
window.addEventListener('pageshow',refreshTimerNow);
document.addEventListener('visibilitychange',refreshTimerNow);
document.addEventListener('resume',refreshTimerNow);

function bindTimer(){document.querySelectorAll('[data-select-index]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.selectIndex);if(Number.isInteger(i)&&data.subjects[i]){selectedSubject=data.subjects[i];render()}});$('#startBtn').onclick=()=>{if(timerId)pauseTimer();else{startTimer();render()}};$('#finishBtn').onclick=finishSession;$('#historyBtn').onclick=()=>{page='history';syncNav();render()};$('#addSubject').onclick=addSubject;document.querySelectorAll('[data-rename-index]').forEach(b=>b.onclick=()=>renameSubject(Number(b.dataset.renameIndex)));document.querySelectorAll('[data-delete-index]').forEach(b=>b.onclick=()=>deleteSubject(Number(b.dataset.deleteIndex)));}

async function addSubject(){const name=await subjectDialog('Add subject','','Add subject');if(name===null)return;if(data.subjects.some(s=>s.toLowerCase()===name.toLowerCase())){await subjectDialog('Subject already exists',name,'OK');return}data.subjects.push(name);selectedSubject=name;await save();render()}
async function renameSubject(index){if(!Number.isInteger(index)||!data.subjects[index])return;const old=data.subjects[index],name=await subjectDialog('Edit subject',old,'Save changes');if(name===null||name===old)return;if(data.subjects.some((s,i)=>i!==index&&s.toLowerCase()===name.toLowerCase())){await subjectDialog('Subject already exists',name,'OK');return}data.subjects[index]=name;data.sessions.forEach(s=>{if(s.subject===old)s.subject=name});if(selectedSubject===old)selectedSubject=name;await save();render()}
async function deleteSubject(index){if(!Number.isInteger(index)||!data.subjects[index])return;const name=data.subjects[index];const ok=await confirmDialog('Delete subject?',`Delete “${name}” from your subject list? Existing session history will be preserved.`);if(!ok)return;data.subjects.splice(index,1);if(selectedSubject===name)selectedSubject=data.subjects[0]||'';await save();render()}
function finishSession(){if(timerId){elapsed=liveElapsed();clearInterval(timerId);timerId=null}if(elapsed<2){elapsed=0;timerStartedAt=0;timerBaseElapsed=0;render();return}data.sessions.push({id:crypto.randomUUID(),started:new Date(Date.now()-elapsed*1000).toISOString(),seconds:elapsed,subject:selectedSubject||'Uncategorized'});elapsed=0;timerStartedAt=0;timerBaseElapsed=0;save().then(render)}
function calendarPage(){let y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),cells=[];for(let i=0;i<first.getDay();i++)cells.push('<div class="day emptyday"></div>');for(let d=1;d<=last.getDate();d++){let k=key(new Date(y,m,d)),v=dayTotal(k);cells.push(`<button class="day ${v?'hasdata':''}" data-day="${k}"><span>${d}</span><b>${v?fmtShort(v):'—'}</b></button>`)}$('#content').innerHTML=`<div class="page"><div class="calendar-card card"><div class="monthnav"><button id="calPrev">←</button><div><span class="eyebrow2">MONTH</span><h2>${viewDate.toLocaleString('en',{month:'long',year:'numeric'})}</h2></div><button id="calNext">→</button></div><div class="calendar-total">Total study <b>${hours(monthSessions(y,m).reduce((a,s)=>a+s.seconds,0))}h</b></div><div class="weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div><div class="card mt"><div class="cardhead"><h3>${y} Year Heatmap</h3><div class="year-controls"><button id="yearPrev">←</button><b>${y}</b><button id="yearNext">→</button></div></div>${yearHeatmap(y,true)}</div></div>`;$('#calPrev').onclick=()=>{viewDate=new Date(y,m-1,1);render()};$('#calNext').onclick=()=>{viewDate=new Date(y,m+1,1);render()};$('#yearPrev').onclick=()=>{viewDate=new Date(y-1,m,1);render()};$('#yearNext').onclick=()=>{viewDate=new Date(y+1,m,1);render()};document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{let [yy,mm,dd]=b.dataset.day.split('-').map(Number);showDay(yy,mm-1,dd)})}
function showDay(y,m,d){let k=key(new Date(y,m,d)),rows=data.sessions.filter(s=>key(s.started)===k).sort((a,b)=>new Date(a.started)-new Date(b.started));alert(`${new Date(y,m,d).toLocaleDateString()}\n\nStudy time: ${fmt(rows.reduce((a,s)=>a+s.seconds,0))}\nSessions: ${rows.length}\n${rows.map(s=>`${s.subject} — ${fmt(s.seconds)}`).join('\n')||'No sessions'}`)}
function analyticsPage(){let y=statsYear,ss=data.sessions.filter(s=>new Date(s.started).getFullYear()===y),totalY=ss.reduce((a,s)=>a+s.seconds,0);$('#content').innerHTML=`<div class="page"><div class="yearbar"><button id="syPrev">←</button><div><span class="eyebrow2">YEAR</span><h2>${y}</h2></div><button id="syNext">→</button></div><div class="grid g4"><div class="card metric"><span class="eyebrow2">YEAR TOTAL</span><strong>${hours(totalY)}h</strong><small>${ss.length} sessions</small></div><div class="card metric"><span class="eyebrow2">ACTIVE DAYS</span><strong>${new Set(ss.map(s=>key(s.started))).size}</strong><small>in ${y}</small></div><div class="card metric"><span class="eyebrow2">DAILY AVG</span><strong>${hours(totalY/365)}h</strong><small>calendar-day average</small></div><div class="card metric"><span class="eyebrow2">LONGEST</span><strong>${fmt(Math.max(0,...ss.map(s=>s.seconds)))}</strong><small>single session</small></div></div><div class="grid g2 mt"><div class="card"><h3>Monthly trend</h3>${monthlyTrend(y)}</div><div class="card"><h3>Subject breakdown</h3>${pie(subjectTotals(y))}</div></div><div class="grid g2 mt"><div class="card"><h3>24-hour study pattern</h3>${hourBars(ss)}</div><div class="card"><h3>Weekday pattern</h3>${weekdayBars(ss)}</div></div><div class="card mt"><h3>Monthly archive</h3>${monthlyTable(y)}</div></div>`;$('#syPrev').onclick=()=>{statsYear=y-1;render()};$('#syNext').onclick=()=>{statsYear=y+1;render()}}
function consistencyPage(){let ss=data.sessions,byHour=Array(24).fill(0),byDay=Array(7).fill(0),sessions=Array(24).fill(0);ss.forEach(s=>{let d=new Date(s.started);byHour[d.getHours()]+=s.seconds;sessions[d.getHours()]++ ;byDay[d.getDay()]+=s.seconds});let peak=byHour.indexOf(Math.max(...byHour));$('#content').innerHTML=`<div class="page"><div class="grid g2"><div class="card"><h3>When you study best</h3><div class="peak">${String(peak).padStart(2,'0')}:00</div><div class="muted">Your highest recorded study-time window</div>${hourBars(ss)}</div><div class="card"><h3>Weekday effectiveness</h3>${weekdayBars(ss)}<div class="muted">Based on total recorded study time, not a hard-coded score.</div></div></div><div class="card mt"><h3>Consistency heatmap</h3>${yearHeatmap(new Date().getFullYear(),true)}</div><div class="grid g3 mt"><div class="card metric"><span class="eyebrow2">ACTIVE DAYS</span><strong>${new Set(ss.map(s=>key(s.started))).size}</strong><small>days you actually showed up</small></div><div class="card metric"><span class="eyebrow2">SESSIONS</span><strong>${ss.length}</strong><small>completed sessions</small></div><div class="card metric"><span class="eyebrow2">AVG SESSION</span><strong>${ss.length?fmt(total()/ss.length):'00:00:00'}</strong><small>average duration</small></div></div></div>`}
function historyPage(){let rows=[...data.sessions].sort((a,b)=>new Date(b.started)-new Date(a.started));$('#content').innerHTML=`<div class="page"><div class="card"><div class="cardhead"><div><h3>Session history</h3><div class="muted">This is the raw record behind your graphs and calendars.</div></div><div class="history-count">${rows.length} sessions</div></div>${rows.length?`<div class="tablewrap"><table class="table"><thead><tr><th>Date & time</th><th>Subject</th><th>Duration</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td>${new Date(s.started).toLocaleString()}</td><td>${esc(s.subject)}</td><td>${fmt(s.seconds)}</td><td><button class="iconbtn danger" data-remove="${s.id}">Delete</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No sessions yet. Start the timer to create your first record.</div>'}</div></div>`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Delete this session? This will update all statistics.')){data.sessions=data.sessions.filter(s=>s.id!==b.dataset.remove);save().then(render)}})}
function growthPage(){let h=total()/3600,st=[0,5,20,50,100,200,350,550,800,1100,1500,2000,2700,3600,4800,6200,8000,10000],names=['Seed','Sprout','Seedling','Young Tree','Mature','Blooming','Tree','Ancient','Legendary','Mythic','Eternal','Ascendant','Titan','Colossus','World Tree','Evergreen','Mastery','Complete'];let i=st.findIndex((v,j)=>h>=v&&h<(st[j+1]??Infinity));if(i<0)i=st.length-1;let next=st[i+1]??10000,base=st[i],pct=i===st.length-1?100:(h-base)/(next-base)*100;$('#content').innerHTML=`<div class="page"><div class="card tree-card"><span class="eyebrow2">GROWTH</span><h2>${names[i]}</h2><div class="tree">${treeSvg(Math.min(1,h/10000))}</div><strong class="tree-hours">${h.toFixed(1)} hours</strong><div class="muted">${i===st.length-1?'Final growth stage reached.':'Next: '+names[i+1]+' at '+next.toLocaleString()+'h'}</div></div><div class="card mt"><div class="cardhead"><b>Progress to next stage</b><b>${pct.toFixed(0)}%</b></div><div class="growthbar"><div style="width:${pct}%"></div></div></div><div class="card mt"><h3>Growth journey</h3><div class="growth-grid">${st.map((v,j)=>`<div class="growth-stage ${j<=i?'done':''}"><b>${names[j]}</b><small>${v.toLocaleString()}h</small></div>`).join('')}</div></div></div>`}
function subjectTotals(year=null){return data.subjects.map(x=>[x,data.sessions.filter(s=>(year===null||new Date(s.started).getFullYear()===year)&&s.subject===x).reduce((a,s)=>a+s.seconds,0)]).filter(x=>x[1]>0).concat([['Other',data.sessions.filter(s=>!data.subjects.includes(s.subject)&&(year===null||new Date(s.started).getFullYear()===year)).reduce((a,s)=>a+s.seconds,0)]]).filter(x=>x[1]>0)}
function fmtShort(s){if(s<60)return `${s}s`;if(s<3600)return `${Math.floor(s/60)}m`;return `${(s/3600).toFixed(1)}h`}
function dailyBars(n){let vals=[];for(let i=n-1;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);vals.push([d.getDate(),dayTotal(key(d))])}let mx=Math.max(1,...vals.map(x=>x[1]));return `<div class="chart">${vals.map(x=>`<div class="barwrap"><div class="bar" style="height:${Math.max(3,x[1]/mx*170)}px"></div><span>${x[0]}</span></div>`).join('')}</div>`}
function monthlyTrend(y){let vals=Array.from({length:12},(_,m)=>monthSessions(y,m).reduce((a,s)=>a+s.seconds,0)),mx=Math.max(1,...vals);return `<div class="chart tall">${vals.map((v,i)=>`<div class="barwrap"><div class="bar" style="height:${Math.max(3,v/mx*190)}px"></div><span>${['J','F','M','A','M','J','J','A','S','O','N','D'][i]}</span></div>`).join('')}</div>`}
function monthBars(y,m){let days=new Date(y,m+1,0).getDate(),vals=Array.from({length:days},(_,i)=>dayTotal(key(new Date(y,m,i+1)))),mx=Math.max(1,...vals);return `<div class="chart tall">${vals.map((v,i)=>`<div class="barwrap"><div class="bar" style="height:${Math.max(2,v/mx*180)}px"></div><span>${i+1}</span></div>`).join('')}</div>`}
function hourBars(ss){let vals=Array(24).fill(0);ss.forEach(s=>vals[new Date(s.started).getHours()]+=s.seconds);return barChart(vals,24,i=>String(i).padStart(2,'0'))}
function weekdayBars(ss){let vals=Array(7).fill(0);ss.forEach(s=>vals[new Date(s.started).getDay()]+=s.seconds);return barChart(vals,7,i=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i])}
function barChart(vals,count,label){let mx=Math.max(1,...vals);return `<div class="chart tall">${vals.slice(0,count).map((v,i)=>`<div class="barwrap"><div class="bar" style="height:${Math.max(3,v/mx*180)}px"></div><span>${label(i)}</span></div>`).join('')}</div>`}
function pie(items){let totalV=items.reduce((a,x)=>a+x[1],0);if(!totalV)return '<div class="empty">No recorded subject data yet.</div>';let angle=-Math.PI/2,r=78,c=100,colors=['#4fa3ff','#58d6a0','#a88cff','#ffad6b','#ff6f91','#67d9ef'],paths='';items.forEach((x,i)=>{let a=x[1]/totalV*Math.PI*2,x1=c+r*Math.cos(angle),y1=c+r*Math.sin(angle),x2=c+r*Math.cos(angle+a),y2=c+r*Math.sin(angle+a);paths+=`<path d="M ${c} ${c} L ${x1} ${y1} A ${r} ${r} 0 ${a>Math.PI?1:0} 1 ${x2} ${y2} Z" fill="${colors[i%colors.length]}"/>`;angle+=a});return `<div class="piebox"><svg viewBox="0 0 200 200"><circle cx="100" cy="100" r="82" fill="#09131e"/>${paths}<circle cx="100" cy="100" r="47" fill="#09131e"/></svg><div class="legend">${items.map((x,i)=>`<div><i style="background:${colors[i%colors.length]}"></i><span>${esc(x[0])}</span><b>${hours(x[1])}h</b></div>`).join('')}</div></div>`}
function heatmapCells(y){let start=new Date(y,0,1),cells='';for(let i=0;i<start.getDay();i++)cells+='<div></div>';for(let d=1;d<=365+(new Date(y,1,29).getMonth()===1?1:0);d++){let date=new Date(y,0,d);let v=dayTotal(key(date)),level=v===0?0:v<1800?1:v<3600?2:v<7200?3:4;cells+=`<div class="hcell h${level}" title="${key(date)} · ${fmtShort(v)}"></div>`}return cells}
function yearHeatmap(y,full){return `<div class="heatwrap ${full?'full':''}"><div class="heatgrid">${heatmapCells(y)}</div><div class="heatlegend"><span>Less</span><i class="hcell h0"></i><i class="hcell h1"></i><i class="hcell h2"></i><i class="hcell h3"></i><i class="hcell h4"></i><span>More</span></div></div>`}
function monthlyTable(y){return `<div class="monthtable">${Array.from({length:12},(_,m)=>{let t=monthSessions(y,m).reduce((a,s)=>a+s.seconds,0),a=new Set(monthSessions(y,m).map(s=>key(s.started))).size;return `<div><b>${new Date(y,m,1).toLocaleString('en',{month:'long'})}</b><span>${hours(t)}h</span><small>${a} active days</small></div>`}).join('')}</div>`}
function recentRows(n){let rows=[...data.sessions].sort((a,b)=>new Date(b.started)-new Date(a.started)).slice(0,n);return rows.length?`<div class="session-list">${rows.map(s=>`<div class="session-row"><div><b>${esc(s.subject)}</b><small>${new Date(s.started).toLocaleString()}</small></div><strong>${fmt(s.seconds)}</strong></div>`).join('')}</div>`:'<div class="empty">No sessions recorded yet.</div>'}
function streak(){let set=new Set(data.sessions.map(s=>key(s.started))),n=0,d=new Date();while(set.has(key(d))){n++;d.setDate(d.getDate()-1)}return n}
function treeSvg(p){let leaves=Math.round(10+p*55),size=1+p*.55;return `<svg viewBox="0 0 360 400"><defs><radialGradient id="treebg"><stop stop-color="#173828"/><stop offset="1" stop-color="#08131c"/></radialGradient></defs><circle cx="180" cy="205" r="155" fill="url(#treebg)" opacity=".72"/><path d="M180 350 Q160 280 180 170" stroke="#866243" stroke-width="18" fill="none" stroke-linecap="round"/><path d="M180 260 Q125 220 100 175 M180 245 Q230 205 255 160 M180 210 Q145 175 125 130 M180 200 Q215 160 235 120" stroke="#5d946e" stroke-width="7" fill="none" stroke-linecap="round"/>${Array.from({length:leaves},(_,i)=>{let a=i*2.399,rad=35+(i%9)*10,x=180+Math.cos(a)*rad,y=135+Math.sin(a)*rad*.7;return `<circle cx="${x}" cy="${y}" r="${6+(i%4)*2}" fill="${i%3===0?'#75d49a':'#3e9c68'}"/>`}).join('')}<circle cx="180" cy="350" r="24" fill="#6d4c34"/></svg>`}
function syncNav(){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
function bindNav(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;syncNav();render()});$('#quickTimer').onclick=()=>{page='timer';syncNav();render()};$('#backup').onclick=()=>window.studyAPI.backup();$('#restore').onclick=async()=>{let d=await window.studyAPI.restore();if(d){data={...data,...d};if(!Array.isArray(data.sessions))data.sessions=[];if(!Array.isArray(data.subjects))data.subjects=[];save().then(render)}}}
(async()=>{try{let d=await window.studyAPI.load();if(d&&typeof d==='object')data={...data,...d};if(!Array.isArray(data.sessions))data.sessions=[];if(!Array.isArray(data.subjects))data.subjects=[];bindNav();render()}catch(e){document.querySelector('#content').innerHTML=`<div class="page"><div class="card"><h2>Startup error</h2><pre>${esc(e.stack||e.message)}</pre></div></div>`}})();
